const createStyles = (theme) => ({
  modal: { flex: 1, backgroundColor: theme.colors.surface },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  title: { fontSize: 20, fontWeight: "600", color: theme.colors.primaryText, marginBottom: 4 },
  text: { fontSize: 16, color: theme.colors.primaryText },
  caption: { fontSize: 14, color: theme.colors.primaryText, marginVertical: 6 },
  content: { padding: 16, gap: 12 },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  button: {
    minHeight: 44,
    minWidth: 44,
    padding: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.disabledText,
  },
  selected: { borderWidth: 2, borderColor: theme.colors.primaryText },
  disabled: { opacity: 0.5 },
  preview: {
    height: 110,
    borderWidth: 1,
    borderColor: theme.colors.disabledText,
    borderRadius: 8,
    overflow: "hidden",
  },
  secondaryPreview: { height: 190 },
  webview: { flex: 1 },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: theme.colors.disabledText,
    borderRadius: 8,
    paddingHorizontal: 12,
    color: theme.colors.primaryText,
    fontSize: 18,
  },
  swatch: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.colors.disabledText,
  },
  selectedSwatch: { borderWidth: 4, borderColor: theme.colors.primaryText },
  legend: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: theme.colors.disabledText,
  },
});

export default createStyles;
