# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SundarGutka' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SundarGutka
  pod 'Firebase/Core'

  target 'SundarGutkaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SundarGutka-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SundarGutka-tvOS

  target 'SundarGutka-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
