export default {
  ABOUT: "About",
  INDEX_REORDER: "Index Reorder",
  ANDROID: "android",
  KHALIS_FOUNDATION_URL: "https://khalisfoundation.org",
  BANI_DB_URL: "https://www.banidb.com/",
  MEDIUM: "MEDIUM",
  READER: "Reader",
  FOLDER_BANI: "FolderBani",
  AMBIENT: "Ambient",
  DEFAULT: "DEFAULT",
  GURBANI_AKHAR_SG: "GurbaniAkharSG",
  GURBANI_AKHAR_HEAVY_SG: "GurbaniAkharHeavySG",
  GURBANI_AKHAR_THICK_SG: "GurbaniAkharThickSG",
  GURBANI_AKHAR_TRUE: "GurbaniAkharTrue",
  HOME_SCREEN: "Home Screen",
  GURBANI_AKHAR_HEAVY_TRUE: "GurbaniAkharHeavyTrue",
  SETTINGS: "Settings",
  EXTRA_LONG: "EXTRA_LONG",
  LONG: "LONG",
  SHORT: "SHORT",
  EXISTS_BUDDHA_DAL: "existsBuddhaDal",
  EXISTS_TAKSAL: "existsTaksal",
  EXISTS_MEDIUM: "existsMedium",
  EXISTS_SGPS: "existsSGPC",
  DB: "gutka.db",
  VISHRAAM_GRADIENT: "VISHRAAM_GRADIENT",
  VISHRAAM_COLORED: "VISHRAAM_COLORED",
  MAST_SABH_MAST: "MAST_SABH_MAST",
  PORTRAIT: "portrait",
  LANDSCAPE: "landscape",
  THEME: "Theme",
};
