export default {
  COLOR: {
    TOOLBAR_COLOR: "#2a3381",
    READER_HEADER_COLOR: "#171d47dd",
    READER_FOOTER_COLOR: "#171d47dd",
    READER_STATUS_BAR_COLOR: "#363C5D",
    READER_STATUS_BAR_COLOR_NIGHT_MODE:"#141a3c",
    TOOLBAR_COLOR_ALT: "#DEBB0A",
    TOOLBAR_COLOR_ALT_NIGHT_MODE: "#99852c",
    TOOLBAR_COLOR_ALT2: "#003436",
    TOOLBAR_TINT: "#fff",
    SETTING_SWITCH_COLOR: "#5195ea",
    SETTING_SWITCH_THUMB: "#A7CAF8",
    ACTIVE_VIEW_COLOR_NIGHT_MODE: "#2d2d2d",
    INACTIVE_VIEW_COLOR_NIGHT_MODE: "#232323",
    ACTIVE_VIEW_COLOR: "#C7C7D7",
    INACTIVE_VIEW_COLOR: "#e9e9ee",
    MODAL_BACKGROUND_NIGHT_MODE: "#202124",
    MODAL_ACCENT_NIGHT_MODE: "#2581df",
    MODAL_ACCENT_NIGHT_MODE_ALT: "#5195ea",
    MODAL_TEXT_NIGHT_MODE: "#fff",
    ENABELED_TEXT_COLOR_NIGHT_MODE: "#2581df",
    DISABLED_TEXT_COLOR_NIGHT_MODE: "#a3a3a3",
    ENABELED_TEXT_COLOR: "#2581df",
    DISABLED_TEXT_COLOR: "#a3a3a3",
    COMPONENT_COLOR_NIGHT_MODE: "#fefefe",
    COMPONENT_COLOR: "#232323"
  }
};