import LocalizedStrings from "react-native-localization";

const Strings = new LocalizedStrings({
  "en-US": {
    about: "About",
    about_1: "We welcome your comments, suggestions, and corrections!",
    about_2: "For information, suggestions, or help, visit us at",
    about_3: "Please respectfully cover your head and remove your shoes when using this app.",
    about_4: "Sundar Gutka utilizes",
    about_5:
      "- the open source gurbani database and api used in many gurbani applications, such as SikhiToTheMax.",
    about_6: "Bhul Chuk Maaf!",
    above_raag_headings: "Above Raag Headings",
    anmol_lipi: "Anmol Lipi",
    app_version: "App Version",
    auto_scroll: "Auto Scroll",
    bani_length: "Bani Length",
    bani_length_alert_1:
      "Throughout the past few centuries, there have been many different “sampardhas” or “jathas” that have been conceived from the core concepts of Sikhi and Gurmat. These sampardhas often have different opinions and thoughts about some aspects of Sikh history, Gurbani and Rehat, but still fall collectively under the united Khalsa Panth and, most importantly, the Akaal Takht. The Akaal Takht is the highest order and institution that all Sikhs adhere to.",
    bani_length_alert_2:
      "These differences have also brought about different recommendations about compiled Baanis and the Paath (prayers) that we read on a daily basis which makes it difficult to create a single Sundar Gutka app with a single version of Paath that would satisfy everyone.",
    bani_length_alert_3:
      "We therefore have created the option to select lengths of what Paath you do that apply to four of the main Banis read most often. These have been structured in relation to length but all have a minimum of the SGPC standard or fall under the Akaal Takht. We do not include any versions that are by sampardhas excommunicated by the Akaal Takht as a standard.",
    bani_length_alert_4:
      "For those who may be confused about which version to begin reading these Banis, we recommend reading the longest Bani because the more we read and recite, the better it is for our souls. However, for beginners, we would suggest to start with the “short” setting and change to increase the length setting in future once you are comfortable, confident and have more time.",
    bani_length_alert_5:
      "Here is a breakdown of the lengths and which sampardhas typically use them:-",
    bani_length_alert_6: "SHORT: This is the minimum SGPC/Akaal Takht standard.",
    bani_length_alert_7:
      "MEDIUM: Typically read by followers of the Akhand Keertani Jatha and others.",
    bani_length_alert_8: "LONG: Typically read by followers of Damdami Taksaal and others.",
    bani_length_alert_9: "EXTRA LONG: Most popular amongst followers of Buddha Dal.",
    bani_length_message_1:
      "Based on user feedback, we know there are many different variations of certain Banis out there that people read. To make sure you get the best experience from our app, please choose a preference below which best describes your preferences.",
    bani_length_message_2:
      "This will be a one-time setup, but you can change these settings at any time by going to Settings > Bani Length in the app.",
    baniDB: "BaniDB",
    bani_options: "Bani Options",
    banidb_living_default: "BaniDB Living (default)",
    bookmarks: "Bookmarks",
    cancel: "Cancel",
    choose_your_preference: "Choose your preference",
    collect_statistics: "Collect Statistics",
    colored_words: "Colored Words",
    confirm_exit: "Are you sure you want to exit?",
    created_by: "Created By",
    current_saroops_default: "Current Saroops (default)",
    dark_mode: "Dark Mode",
    default: "Default",
    delete: "Delete",
    display_options: "Display Options",
    donate: "Donate",
    edit_bani_order: "Edit Bani Order",
    en_translations: "English Translations",
    english: "English",
    es_translations: "Spanish Translations",
    exit: "Exit",
    exit_sundar_gutka: "Exit Sundar Gutka",
    extra_large: "Extra Large",
    extra_long: "Extra Long",
    extra_small: "Extra Small",
    font_face: "Font Face",
    font_size: "Font Size",
    gradient_background: "Gradient Background",
    gurbani_akhar_default: "Gurbani Akhar (default)",
    gurbani_akhar_heavy: "Gurbani Akhar Heavy",
    gurbani_akhar_think: "Gurbani Akhar Thick",
    hide_status_bar: "Hide Status Bar",
    hindi: "Hindi",
    iGurbani: "iGurbani",
    ipa: "International Phonetic Alphabet",
    keep_awake: "Keep Screen Awake",
    khalis_foundation: "Khalis Foundation",
    language: "Language",
    large: "Large",
    larivaar: "Larivaar",
    larivaar_assist: "Larivaar Assist",
    long: "Long",
    manglacharan_position: "Manglacharan Position",
    mast_sabh_mast: "Mast Sabh Mast",
    medium: "Medium",
    need_help_deciding: "Need help deciding?",
    notification_text: "Notification Text",
    ok: "OK",
    other_options: "Other Options",
    padchhed_settings: "Padchhed Settings",
    paragraph_mode: "Paragraph Mode",
    pick_a_time: "Pick a Time",
    pu_translations: "Punjabi Translations",
    reminder_options: "Reminder Options",
    reminder_sound: "Reminder Sound",
    reminders: "Reminders",
    reset: "Reset",
    reset_reminder_text: "Do you want to restore reminders to the default values?",
    reset_reminders: "Reset Reminders",
    sat_subham_sat_default: "Sat Subham Sat (default)",
    set_reminder_options: "Set Reminder Options",
    settings: "Settings",
    shahmukhi: "Shahmukhi",
    short: "Short",
    show_vishraams: "Show Vishraams",
    small_default: "Small (default)",
    sttm2: "STTM 2",
    sundar_gutka: "Sundar Gutka",
    tap_more_info: "Tap here for more information",
    time_for: "Time for",
    translations: "Translations",
    transliteration: "Transliteration",
    vishraam_options: "Vishraam Options",
    vishraam_source: "Vishraam Source",
    waheguru_soul: "Waheguru Soul",
    wake_up_jap: "Wake Up Jap",
    khalsa_sundar_gutka: "Kwlsw suMdr gutkw",
    fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
    sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    theme: "Theme",
    errorTitle: "Something Went Wrong",
    errorMessage:
      "Click on the Reload Button to try again. If this error persists, you can click on report button to send us the error log.",
    errorReload: "Reload",
    errorReport: "Report",
  },
  hi: {
    about: "हमारे बारे",
    about_1: "हम आप के सुझाव और टिप्पणिओं का स्वागत करते हैं।",
    about_2: "और जानकारी, मदद या सुझाव के लिए यहां जाएँ।",
    about_3: "एप्प का इस्तेमाल करने से पहले सत्कार सहत अपने जूते उतार के सिर ढक लें",
    about_4: "सुंदर गुटका इस्तेमाल करता है",
    about_5: "-ओपन सोर्स डाटाबेस और बहुत सारी गुरबाणी एप्प जैसे SikhiToTheMax",
    about_6: "भूलों की क्षमा !",
    above_raag_headings: "राग शीर्षक",
    anmol_lipi: "अनमोल लिपि",
    app_version: "एप्प वर्जन",
    auto_scroll: "ऑटो स्क्रॉल",
    bani_length: "बाणी लंबाई",
    bani_length_alert_1:
      "पिछले कुछ सदियों में, कई सम्प्रदायें और संगठन पैदा हुई हैं, जो सिख सिद्धांत और गुरुमत पर केंद्रित हैं। हालांकि इन संप्रदायों में सिख इतिहास, गुरबानी और अनुपालन पर मतभेद रहे हैं, पर वे पूर्ण रूप से  खालसा पंथ का हिस्सा बने हुए हैं और उच्चतम अकाल तख्त के बैनर तले ही रह रहे हैं।",
    bani_length_alert_2:
      "इन मतभेदों के कारण, नितनेम की बाणिओं  की लंबाई पर अलग- अलग निर्देश मिलते रहे हैं। इस कारण से, हर एक को संतुष्ट कर देने वाला एक  सुंदर गुटका ऐप बनाना मुश्किल है।",
    bani_length_alert_3:
      "इसीलिए हमने इस ऐप में चार सबसे ज्यादा पढ़ी जाने वाली बाणिओं की लंबाई चुनने की सुविधा दी है। इन चयनों को बाणी की लंबाई के अनुसार व्यवस्थित किया गया है लेकिन सभी बाणी अकाल तख्त द्वारा अनुमोदित मानकों के अनुसार हैं। हमने इस एप में अकाल तख्त द्वारा पंथ से बाहर की हुई किसी भी संप्रदाय द्वारा इस्तेमाल किए जाने वाली बाणी नहीं शामिल की है।",
    bani_length_alert_4:
      "यदि आप असमंजस में हैं कि किस बाणी के साथ शुरू करें, तो हमारी सलाह सबसे लंबी बाणी है क्योंकि जितना अधिक हम बाणी का अभ्यास करेंगे, हमारी आत्मा के लिए उतना ही अच्छा होगा। यदि आप एकदम नए हैं तो आप सबसे छोटी बाणी के साथ शुरुआत कर सकते हैं और जैसे आपका नाम अभ्यास बढ़ता है, आप अधिक बाणी पढ़ सकते हैं।",
    bani_length_alert_5: "बाणिओं को व्यवस्थित उनकी लंबाई और सम्प्रदा के हिसाब से किआ गया है",
    bani_length_alert_6:
      "छोटी - यह बाणी अकाल तख्त साहिब से परवाणित कम से कम आदेशों के हिसाब से है।",
    bani_length_alert_7: "मध्यम - अखंड कीर्तनी जथा तथा और।",
    bani_length_alert_8: "लम्बी - दमदमी टकसाल तथा और जथे।",
    bani_length_alert_9: "बहुत लम्बी - बुड्ढा दल",
    bani_length_message_1:
      "इस एप में अपना तज़ुर्बा और उत्तम करने के लिए अपनी पसंद के हिसाब से बाणी का चयन करें",
    bani_length_message_2:
      "यह चयन आपको एक बार ही करना पड़ेगा लेकिन आप कभी भी settings >bani  length में जाकर अपना चयन बदल सकते हैं।",
    baniDB: "BaniDB",
    bani_options: "बाणी विकल्प",
    banidb_living_default: "BaniDB जीवित (मूल)",
    bookmarks: "बुकमार्क",
    cancel: "रहने दो",
    choose_your_preference: "अपनी पसंद के हिसाब से चयन करें",
    collect_statistics: "आंकड़े इकट्ठे करो",
    colored_words: "रंगदार शब्द",
    confirm_exit: "किआ आप बाहर जाना चाहते हो?",
    created_by: "बनाई गयी",
    current_saroops_default: "मौजूदा सरूप",
    dark_mode: "गहरा mode",
    default: "मूल",
    delete: "मिटा दे",
    display_options: "डिस्प्ले विकल्प",
    donate: "दान",
    edit_bani_order: "बाणी की तरतीब बदलें",
    en_translations: "अंग्रेजी अनुवाद",
    english: "अंग्रेजी",
    es_translations: "स्पैनिश अनुवाद",
    exit: "बाहर निकलें",
    exit_sundar_gutka: "सुंदर गुटके से बाहर निकलें",
    extra_large: "बहुत बड़ा",
    extra_long: "बहुत लम्बा",
    extra_small: "बहुत छोटा",
    font_face: "फॉन्ट का नाम",
    font_size: "फॉन्ट का आकार",
    gradient_background: "ढाल पृष्ठभूमि",
    gurbani_akhar_default: "गुरबाणी अक्षर (मूल)",
    gurbani_akhar_heavy: "गुरबाणी अक्षर भारी ",
    gurbani_akhar_think: "गुरबाणी अक्षर मोटे",
    hide_status_bar: "स्टेटस बार को छिपा दें",
    hindi: "हिंदी",
    iGurbani: "iGurbani",
    ipa: "इंटरनेशनल फ़ोनेटिक एल्फाबेट",
    keep_awake: "स्क्रीन को चलती रखें",
    khalis_foundation: "खालिस फाउंडेशन",
    language: "भाषा",
    large: "बड़ा",
    larivaar: "लड़ीवार",
    larivaar_assist: "लड़ीवार मदद के साथ",
    long: "लम्बा",
    manglacharan_position: "मंगलाचरण की जगह",
    mast_sabh_mast: "मस्त सभ मस्त",
    medium: "मध्यम",
    need_help_deciding: "चयन करने में मदद चाहिए?",
    notification_text: "नोटीफिकेशन अक्षर",
    ok: "ठीक",
    other_options: "और विकल्प",
    padchhed_settings: "पदच्छेद विकल्प",
    paragraph_mode: "पैरा विकल्प",
    pick_a_time: "समें का चुनाव",
    pu_translations: "पंजाबी अनुवाद",
    reminder_options: "याद करवाएं",
    reminder_sound: "याद करवाने वाली ध्वनि",
    reminders: "अनुस्मारक",
    reset: "शुरू से",
    reset_reminder_text: "किआ आप याद करवाने विकल्प मूल रूप में लगाने चाहते हो?",
    reset_reminders: "याद करवाने वाले विकल्प शुरू से करो",
    sat_subham_sat_default: "सत सुभम सत",
    set_reminder_options: "याद करवाने वाले विकल्प करें",
    settings: "विकल्प",
    shahmukhi: "शाहमुखी",
    short: "छोटे",
    show_vishraams: "विश्राम दिखलायें",
    small_default: "छोटे (मूल)",
    sttm2: "STTM 2",
    sundar_gutka: "सुंदर गुटका",
    tap_more_info: "और जानकारी के लिए यहां छुएं",
    time_for: "समां है",
    translations: "अनुवाद",
    transliteration: "अक्षरी अनुवाद",
    vishraam_options: "विश्राम विकल्प",
    vishraam_source: "विश्राम का स्रोत",
    waheguru_soul: "वाहेगुरु रूह",
    wake_up_jap: "अमृत समें जाप",
    fateh: "ੴ श्री वाहेगुरु जी की फतेह",
    khalsa_sundar_gutka: "खालसा सुंदर गुटका",
    sg_title: "सुंदर गुटका",
    theme: "थीम",
    errorTitle: "कुछ गलत हो गया",
    errorMessage:
      "पुनः प्रयास करने के लिए पुनर्प्रारंभ बटन पर क्लिक करें। यदि यह त्रुटि बनी रहती है, तो आप हमें त्रुटि लॉग भेजने के लिए रिपोर्ट बटन पर क्लिक कर सकते हैं।",
    errorReload: "पुनर्प्रारंभ",
    errorReport: "रिपोर्ट",
  },
  pa: {
    about: "ਸਾਡੇ ਬਾਰੇ",
    about_1: "ਅਸੀਂ ਤੁਹਾਡੀਆਂ ਟਿੱਪਣੀਆਂ ਅਤੇ ਸੁਝਾਵਾਂ ਨੂੰ ਖਿੜੇ ਮੱਥੇ ਪ੍ਰਵਾਨ ਕਰਦੇ ਆ।",
    about_2: "ਹੋਰ ਜਾਣਕਾਰੀ, ਸੁਝਾਅ ਯਾ ਮੱਦਦ ਲਈ ਏਥੇ ਜਾਓ",
    about_3: "ਐਪ ਨੂੰ ਵਰਤਣ ਲੱਗੇ ਸਤਿਕਾਰ ਸਹਿਤ ਆਪਣੇ ਜੋੜੇ ਲਾਹ ਕੇ ਸਿਰ ਢੱਕ ਲਓ",
    about_4: "ਸੁੰਦਰ ਗੁਟਕਾ ਵਰਤਦਾ ਹੈ",
    about_5: "- ਓਪਨ ਸੋਰਸ ਗੁਰਬਾਣੀ ਡਾਟਾਬੇਸ ਅਤੇ ਬਹੁਤ ਸਾਰੀਆਂ ਗੁਰਬਾਣੀ ਐਪਾਂ ਜਿਵੇਂ ਕੇ SikhiToTheMax",
    about_6: "ਭੁੱਲ ਚੁੱਕ ਮਾਫ !",
    above_raag_headings: "ਰਾਗ ਸਿਰਨਾਵੇਂ",
    anmol_lipi: "ਅਨਮੋਲ ਲਿਪੀ",
    app_version: "ਐਪ ਵਰਜ਼ਨ",
    auto_scroll: "ਆਟੋ ਸਕਰੋਲ",
    bani_length: "ਬਾਣੀ ਲੰਬਾਈ",
    bani_length_alert_1:
      "ਬੀਤੀਆਂ ਕੁਝ ਸਦੀਆਂ ਦੌਰਾਨ ਅਨੇਕਾਂ ਅਜਿਹੀਆਂ ਸੰਪਰਦਾਵਾਂ ਤੇ ਜੱਥੇਬੰਦੀਆਂ ਪੈਦਾ ਹੋਈਆਂ ਜਿਨ੍ਹਾਂ ਦਾ ਧੁਰਾ ਸਿੱਖੀ ਸਿਧਾਂਤ ਅਤੇ ਗੁਰਮਤਿ ਰਿਹਾ। ਭਾਵੇਂ ਇਹਨਾਂ ਸੰਪਰਦਾਵਾਂ ਵਿੱਚ ਸਿੱਖ ਇਤਿਹਾਸ, ਗੁਰਬਾਣੀ ਅਤੇ ਰਹਿਤ ਨੂੰ ਲੈ ਕੇ ਆਪਸੀ ਮਤਭੇਦ ਰਹੇ ਹਨ, ਪਰ ਸਮੂਹ ਤੌਰ ਤੇ ਖਾਲਸਾ ਪੰਥ ਦੇ ਹਿੱਸੇ ਵਜੋਂ ਹੀ ਵਿਚਰੀਆਂ ਹਨ ਤੇ ਸੱਭ ਤੋਂ ਵੱਧ ਕੇ ਸਰਬ ਉੱਚ ਅਕਾਲ ਤਖਤ ਦੇ ਝੰਡੇ ਹੇਠ ਹੀ ਰਹੀਆਂ (ਰਹਿੰਦੀਆਂ) ਹਨ।",
    bani_length_alert_2:
      "ਇਹਨਾਂ ਵਖਰੇਵਿਆਂ ਦੇ ਕਾਰਨ ਨਿਤਨੇਮ ਦੀਆਂ ਸੰਪਾਦਿਤ ਬਾਣੀਆਂ ਦੀ ਲੰਬਾਈ ਉੱਤੇ ਵੀ ਵੱਖੋ ਵੱਖਰੀਆਂ ਹਦਾਇਤਾਂ ਮਿਲਦੀਆਂ ਰਹੀਆਂ ਹਨ। ਇਸ ਕਾਰਨ ਹਰੇਕ ਮਾਈ ਭਾਈ ਦੀ ਸੰਤੁਸ਼ਟੀ ਕਰਵਾ ਸਕਣ ਵਾਲੀ ਇੱਕ ਸਰਬ ਪਰਵਾਨਤ ਸੁੰਦਰ ਗੁਟਕਾ ਐਪ (ਜੁਗਤ) ਤਿਆਰ ਕਰਨੀ ਔਖੀ ਹੋ ਜਾਂਦੀ ਰਹੀ ਹੈ।",
    bani_length_alert_3:
      "ਏਸੇ ਲਈ ਅਸੀਂ ਇਸ ਐਪ (ਜੁਗਤ) ਵਿੱਚ ਆਮ ਤੌਰ ਤੇ ਚਾਰ ਸੱਭ ਤੋਂ ਵੱਧ ਪੜ੍ਹੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਬਾਣੀਆਂ ਦੀ ਲੰਬਾਈ ਚੁਣਨ ਦੀ ਸਹੂਲਤ ਦਿੱਤੀ ਹੈ। ਇਹਨਾਂ ਚੋਣਾਂ ਨੂੰ ਬਾਣੀ ਦੀ ਲੰਬਾਈ ਦੇ ਹਿਸਾਬ ਨਾਲ ਤਰਤੀਬ ਦਿੱਤੀ ਗਈ ਹੈ ਪਰ ਸਾਰੀਆਂ ਹੀ ਬਾਣੀਆਂ ਅਕਾਲ ਤਖਤ ਸਾਹਬ ਵੱਲ੍ਹੋਂ ਪ੍ਰਵਾਨਤ ਮਿਆਰਾਂ ਅਨੁਸਾਰ ਹਨ। ਅਸੀਂ ਅਕਾਲ ਤਖਤ ਤੋਂ ਛੇਕੀ ਹੋਈ ਕਿਸੇ ਵੀ ਸੰਪਰਦਾ ਵੱਲ੍ਹੋਂ ਵਰਤੀ ਜਾਂਦੀ ਬਾਣੀ ਦੀ ਕੋਈ ਵੀ ਵੰਨਗੀ ਇਸ ਜੁਗਤ ਵਿੱਚ ਨਹੀਂ ਪਾਈ",
    bani_length_alert_4:
      "ਜੇ ਤੁਸੀਂ ਇਸ ਉਲਝਣ ਵਿੱਚ ਹੋ ਕੇ ਕਿਸ ਬਾਣੀ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋਂ, ਸਾਡੀ ਸਲਾਹ ਹੈ ਸਭ ਤੋਂ ਲੰਬੀ ਬਾਣੀ ਕਿਉਂਕਿ ਜਿੰਨਾ ਜ਼ਿਆਦਾ ਅਸੀਂ ਬਾਣੀ ਅਭਿਆਸ ਕਰਾਂਗੇ, ਸਾਡੀ ਰੂਹ ਲਈ ਉੰਨਾਂ ਹੀ ਵਧੀਆ ਹੈ।  ਜੇ ਤੁਸੀਂ ਬਿਲਕੁਲ ਨਵੇਂ ਹੋ ਤਾਂ ਤੁਸੀਂ ਸਭ ਤੋਂ ਛੋਟੀ ਬਾਣੀ ਤੋਂ ਵੀ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ ਤੇ ਜਿਵੇਂ ਜਿਵੇਂ ਤੁਹਾਡਾ ਨਾਮ ਅਭਿਆਸ ਵੱਧ ਦਾ ਹੈ, ਤੁਸੀਂ ਜ਼ਿਆਦਾ ਬਾਣੀ ਪੜ੍ਹ ਸਕਦੇ ਓ।",
    bani_length_alert_5: "ਬਾਣੀਆਂ ਦੀ ਤਰਤੀਬ ਉਨ੍ਹਾਂ ਦੀ  ਲੰਬਾਈ ਅਤੇ ਸੰਪਰਦਾਵਾਂ ਦੇ ਹਿਸਾਬ ਨਾਲ ਕੀਤੀ ਗਈ ਹੈ।",
    bani_length_alert_6: "ਛੋਟੀ - ਇਹ ਬਾਣੀ ਅਕਾਲ ਤਖਤ ਸਾਹਿਬ ਵਲ੍ਹੋ ਘੱਟੋ ਘੱਟ ਪ੍ਰਵਾਣਤ ਮਿਆਰਾਂ ਅਨੁਸਾਰ ਹੈ",
    bani_length_alert_7: "ਮੱਧਮ - ਅਖੰਡ ਕੀਰਤਨੀ ਜਥਾ ਅਤੇ ਹੋਰ।",
    bani_length_alert_8: "ਲੰਬੀ - ਦਮਦਮੀ ਟਕਸਾਲ ਅਤੇ ਹੋਰ ਜਥੇ",
    bani_length_alert_9: "ਬਹੁਤ ਲੰਬੀ - ਬੁੱਢਾ ਦਲ",
    bani_length_message_1:
      "ਇਸ ਜੁਗਤ ਨਾਲ ਆਪਣਾ ਤਜਰਬਾ ਹੋਰ ਵਧੀਆ ਕਰਨ ਲਈ ਆਪਣੀ ਪਸੰਦ ਦੇ ਹਿਸਾਬ ਨਾਲ ਬਾਣੀ ਦੀ ਲੰਬਾਈ ਦੀ ਚੋਣ ਕਰੋ।",
    bani_length_message_2:
      "ਇਹ ਚੋਣ ਤੁਹਾਨੂੰ ਇੱਕ ਵਾਰ ਹੀ ਕਰਨੀ ਪਵੇਗੀ ਪਰ ਤੁਸੀਂ ਕਦੇ ਵੀ settings > bani length ਚ ਜਾਕੇ ਆਪਣੀ ਚੋਣ ਬਦਲ ਸਕਦੇ ਹੋ।",
    baniDB: "BaniDB",
    bani_options: "ਬਾਣੀ ਚੋਣਾਂ",
    banidb_living_default: "BaniDB ਜੀਵਿਤ (ਮੂਲ)",
    bookmarks: "ਬੁੱਕਮਾਰਕ",
    cancel: "ਰਹਿਣ ਦਿਓ",
    choose_your_preference: "ਆਪਣੀ ਪਸੰਦ ਦੇ ਹਿਸਾਬ ਨਾਲ ਚੋਣ ਕਰੋ",
    collect_statistics: "ਅੰਕੜੇ ਕੱਠੇ ਕਰੋ",
    colored_words: "ਰੰਗਦਾਰ ਸ਼ਬਦ",
    confirm_exit: "ਕੀ ਤੁਸੀਂ ਬੰਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਓ?",
    created_by: "ਬਣਾਈ ਗਈ",
    current_saroops_default: "ਮੌਜੂਦਾ ਸਰੂਪ",
    dark_mode: "ਗੂੜ੍ਹਾ mode",
    default: "ਮੂਲ",
    delete: "ਮਿਟਾ ਦਿਓ",
    display_options: "ਡਿਸਪਲੇਅ ਚੋਣਾਂ",
    donate: "ਦਾਨ",
    edit_bani_order: "ਬਾਣੀ ਦੀ ਤਰਤੀਬ ਬਦਲੋ",
    en_translations: "ਅੰਗਰੇਜ਼ੀ ਤਰਜਮਾ",
    english: "ਅੰਗਰੇਜ਼ੀ",
    es_translations: "ਸਪੈਨਿਸ਼ ਤਰਜਮਾ",
    exit: "ਬਾਹਰ ਨਿੱਕਲੋ",
    exit_sundar_gutka: "ਸੁੰਦਰ ਗੁਟਕੇ ਤੋਂ ਬਾਹਰ ਨਿੱਕਲੋ",
    extra_large: "ਬਹੁਤ ਵੱਡਾ",
    extra_long: "ਬਹੁਤ ਲੰਬਾ",
    extra_small: "ਬਹੁਤ ਛੋਟਾ",
    font_face: "ਫੋਂਟ ਦਾ ਨਾਮ",
    font_size: "ਫੋਂਟ ਆਕਾਰ",
    gradient_background: "ਗਰੇਡੀਐਂਟ ਪਿਛੋਕੜ",
    gurbani_akhar_default: "ਗੁਰਬਾਣੀ ਅੱਖਰ (ਮੂਲ)",
    gurbani_akhar_heavy: "ਗੁਰਬਾਣੀ ਅੱਖਰ ਭਾਰੇ",
    gurbani_akhar_think: "ਗੁਰਬਾਣੀ ਅੱਖਰ ਮੋਟੇ",
    hide_status_bar: "ਸਟੇਟਸ ਬਾਰ ਨੂੰ ਲਘੋ ਦਿਓ",
    hindi: "ਹਿੰਦੀ",
    iGurbani: "iGurbani",
    ipa: "ਇੰਟਰਨੈਸ਼ਨਲ ਫੋਨੈਟਿਕ ਅਲਫਾਬੈਟ",
    keep_awake: "ਸਕਰੀਨ ਨੂੰ ਚਲਦੀ ਰੱਖੋ",
    khalis_foundation: "ਖਾਲਿਸ ਫਾਊਂਡੇਸ਼ਨ",
    language: "ਭਾਸ਼ਾ",
    large: "ਵੱਡਾ",
    larivaar: "ਲੜੀਵਾਰ",
    larivaar_assist: "ਲੜੀਵਾਰ ਮਦਦ ਦੇ ਨਾਲ",
    long: "ਲੰਬਾ",
    manglacharan_position: "ਮੰਗਲਾਚਰਨ ਦੀ ਥਾਂ",
    mast_sabh_mast: "ਮਸਤ ਸਭ ਮਸਤ",
    medium: "ਦਰਮਿਆਨਾ",
    need_help_deciding: "ਚੋਣ ਕਰਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
    notification_text: "ਨੋਟੀਫਿਕੇਸ਼ਨ ਅੱਖਰ",
    ok: "ਠੀਕ",
    other_options: "ਹੋਰ ਚੋਣਾਂ",
    padchhed_settings: "ਪਦਛੇਦ ਚੋਣ",
    paragraph_mode: "ਪੈਰਾ ਚੋਣ",
    pick_a_time: "ਸਮਾਂ ਚੁਣੋ",
    pu_translations: "ਪੰਜਾਬੀ ਤਰਜਮਾ",
    reminder_options: "ਯਾਦ ਕਰਵਾਓ",
    reminder_sound: "ਯਾਦ ਕਰਵਾਉਣ ਆਲੀ ਆਵਾਜ਼",
    reminders: "ਚੇਤੇ ਕਰਾਉਣ ਲਈ",
    reset: "ਨਵੇਂ ਸਿਰਿਓਂ",
    reset_reminder_text: "ਕੀ ਤੁਸੀਂ ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆਂ ਚੋਣਾਂ ਮੂਲ ਰੂਪ ਤੇ ਲਾਉਣੀਆਂ ਚਾਹੁੰਦੇ ਓ ?",
    reset_reminders: "ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆ ਚੋਣਾਂ ਨੂੰ ਨਵੇਂ ਸਿਰਿਓਂ ਕਰੋ",
    sat_subham_sat_default: "ਸਤ ਸੁਭਮ ਸਤ",
    set_reminder_options: "ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆਂ ਚੋਣਾਂ ਕਰੋ",
    settings: "ਸੈਟਿੰਗ",
    shahmukhi: "ਸ਼ਾਹਮੁਖੀ",
    short: "ਛੋਟੇ",
    show_vishraams: "ਵਿਸ਼ਰਾਮ ਵਿਖਾਓ",
    small_default: "ਛੋਟੇ(ਮੂਲ)",
    sttm2: "STTM 2",
    sundar_gutka: "ਸੁੰਦਰ ਗੁਟਕਾ",
    tap_more_info: "ਹੋਰ ਜਾਣਕਾਰੀ ਲਈ ਇਥੇ ਛੋਹੋ",
    time_for: "ਸਮਾਂ ਹੈ",
    translations: "ਤਰਜਮੇ",
    transliteration: "ਅੱਖਰੀ ਤਰਜਮਾ",
    vishraam_options: "ਵਿਸ਼ਰਾਮ ਚੋਣਾਂ",
    vishraam_source: "ਵਿਸ਼ਰਾਮ ਦਾ ਸਰੋਤ",
    waheguru_soul: "ਵਾਹਿਗੁਰੂ ਰੂਹ",
    wake_up_jap: "ਅੰਮ੍ਰਿਤ ਵੇਲੇ ਦਾ ਜਾਪੁ",
    fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
    khalsa_sundar_gutka: "ਖਾਲਸਾ ਸੁੰਦਰ ਗੁਟਕਾ",
    sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    theme: "ਥੀਮ",
    errorTitle: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
    errorMessage:
      "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨ ਲਈ ਰੀਲੋਡ ਬਟਨ 'ਤੇ ਕਲਿੱਕ ਕਰੋ। ਜੇਕਰ ਇਹ ਤਰੁੱਟੀ ਬਣੀ ਰਹਿੰਦੀ ਹੈ, ਤਾਂ ਤੁਸੀਂ ਸਾਨੂੰ ਗਲਤੀ ਲੌਗ ਭੇਜਣ ਲਈ ਰਿਪੋਰਟ ਬਟਨ 'ਤੇ ਕਲਿੱਕ ਕਰ ਸਕਦੇ ਹੋ।",
    errorReload: "ਰੀਲੋਡ",
    errorReport: "ਰਿਪੋਰਟ",
  },
  fr: {
    about: "Infos",
    about_1: "Veuillez envoyer vos commentaires, suggestions et corrections!",
    about_2: "Pour des informations, des suggestions ou de l'aide, visitez-nous à",
    about_3:
      "Veuillez vous couvrir la tête et retirer vos chaussures par respect lorsque vous utilisez cette application",
    about_4: "Sundar Gutka utilise",
    about_5:
      "- la base de données open source gurbani et l'api utilisées dans de nombreuses applications gurbani, telles que SikhiToTheMax.",
    about_6: "Pardonnez les erreurs [Boule Chouc Màf]",
    above_raag_headings: "Au-Dessus des rubriques raag",
    anmol_lipi: "Anmol Leppi",
    app_version: "Version de l'Application",
    auto_scroll: "Défilement Automatique",
    bani_length: "Longueur de Bani",
    bani_length_alert_1:
      "Au cours des derniers siècles, il y a eu de nombreux «sampardhas» ou «jathas» différents qui ont été conçus à partir des concepts fondamentaux du Sikhi et du Gurmat. Ces sampardhas ont souvent des opinions différentes sur certains aspects de l'histoire sikh, Gurbani et Rehat, mais relèvent toujours collectivement du Khalsa Panth uni et, plus important encore, de l'Akal Takht. L'Akaal Takht est l'ordre le plus élevé et est la plus haute institution à laquelle tous les Sikhs adhèrent.",
    bani_length_alert_2:
      "Ces différences ont également entraîné différentes recommandations sur les Baanis compilés et le Paath (prières) que nous lisons quotidiennement, ce qui rend difficile la création d'une seule application Sundar Gutka avec une seule version de Paath qui satisferait tout le monde.",
    bani_length_alert_3:
      "Nous avons donc créé l'option de sélectionner les longueurs de ce que vous faites. Cette option s'applique à quatre des principaux Banis lus le plus souvent. Celles-ci ont été structurées en fonction de la longueur, mais toutes ont un minimum de la norme SGPC ou relèvent de l'Akaal Takht. En tant que norme, nous n'incluons aucune version par sampardhas excommuniée par l'Akaal Takht.",
    bani_length_alert_4:
      "Pour ceux qui ne savent pas quelle version commencer à lire ces Banis, nous vous recommandons de lire le Bani le plus long car plus nous lisons et récitons, mieux c'est pour nos âmes. Cependant, pour les débutants, nous suggérons de commencer par le réglage «court» et de changer pour augmenter le réglage de la longueur à l'avenir une fois que vous serez à l'aise, confiant et aurez plus de temps.",
    bani_length_alert_5:
      "Voici une explication des longueurs et quels sampardhas les utilisent généralement: -",
    bani_length_alert_6: "COURT: Il s'agit de la norme SGPC / Akaal Takht minimale.",
    bani_length_alert_7:
      "MOYEN: Généralement lu par les adeptes de l'Akhand Kirtani Jatha et d'autres.",
    bani_length_alert_8: "LONG: Généralement lu par les adeptes de Damdami Taksaal et d'autres.",
    bani_length_alert_9: "TRÈS LONG: Le plus populaire parmi les adeptes de Bouddha Dal.",
    bani_length_message_1:
      "Sur la base des commentaires des utilisateurs, nous savons qu'il existe de nombreuses variantes différentes de certains Banis que les gens lisent. Pour vous assurer d'obtenir la meilleure expérience de notre application, veuillez choisir une préférence ci-dessous qui décrit le mieux vos préférences.",
    bani_length_message_2:
      "Ce sera une configuration unique, mais vous pouvez modifier ces paramètres à tout moment en allant dans Paramètres> Longueur de Bani dans l'application.",
    bani_options: "Options de Bani",
    baniDB: "BaniDB",
    banidb_living_default: "BaniDB Vivant (défaut)",
    bookmarks: "Signets",
    cancel: "Annuler",
    choose_your_preference: "Choisissez votre préférence",
    click_more_info: "Cliquez ici pour plus d'informations",
    collect_statistics: "Recueillir des Statistiques",
    colored_words: "Mots en Couleurs",
    confirm_exit: "Voulez-vous vraiment quitter?",
    created_by: "Créé par",
    current_saroops_default: "Saroops actuelles (défaut)",
    dark_mode: "Mode nuit",
    default: "Défaut",
    delete: "Supprimer",
    display_options: "Options d'affichage",
    donate: "Faire un don",
    edit_bani_order: "Modifier la séquence Bani",
    en_translations: "Traductions en anglais",
    english: "Anglais",
    es_translations: "Traductions en castillan",
    exit: "Sortir",
    exit_sundar_gutka: "Sortir de Sundar Gutka",
    extra_large: "Très grande",
    extra_long: "Très longue",
    extra_small: "Très petite",
    font_face: "Police de caractère",
    font_size: "Taille de police",
    gradient_background: "Fond dégradé",
    gurbani_akhar_default: "Gourbani Akhar (défaut)",
    gurbani_akhar_heavy: "Gourbani Akhar Lourde",
    gurbani_akhar_think: "Gourbani Akhar Épaisse",
    hide_status_bar: "Cacher la barre d'état",
    hindi: "Langue hindou",
    iGurbani: "iGurbani",
    ipa: "Alphabet phonétique international",
    keep_awake: "Garder l'écran éveillé",
    khalis_foundation: "La fondation Khalis",
    language: "Langue",
    large: "Grande",
    larivaar: "Larivaar",
    larivaar_assist: "aide larivaar",
    long: "Longue",
    manglacharan_position: "Position Manglacharan",
    mast_sabh_mast: "Mast Sabh Mast",
    medium: "Moyenne",
    need_help_deciding: "Besoin d'aide pour décider?",
    notification_text: "Texte de notification",
    ok: "D'accord",
    other_options: "Autres options",
    padchhed_settings: "Paramètres Padchhed",
    paragraph_mode: "Mode paragraphe",
    pick_a_time: "Choisissez l'heure",
    pu_translations: "Traductions en punjabi",
    reminder_options: "Options de rappel",
    reminder_sound: "Son du rappel",
    reminders: "Rappels",
    reset: "Réinitialiser",
    reset_reminder_text: "Souhaitez-vous restaurer les rappels aux valeurs par défaut?",
    reset_reminders: "Réinitialiser les rappels",
    sat_subham_sat_default: "Sat Subham Sat (défaut)",
    set_reminder_options: "Définir les options de rappel",
    settings: "Paramètres",
    shahmukhi: "Shahmoukhi",
    short: "Courte",
    show_vishraams: "Afficher Vishraams",
    small_default: "Petite (défaut)",
    sttm2: "STTM 2",
    sundar_gutka: "Sundar Gutka",
    tap_more_info: "",
    time_for: "Il est temps de",
    translations: "Traductions",
    transliteration: "Translitération",
    vishraam_options: "Options de Vishraam",
    vishraam_source: "Origine de Vishraam",
    waheguru_soul: "Wahegourou Soul",
    wake_up_jap: "Réveillez-vous Jap",
    khalsa_sundar_gutka: "Kwlsw suMdr gutkw",
    fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
    sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    theme: "Thème",
    errorTitle: "Quelque chose s'est mal passé",
    errorMessage:
      "Cliquez sur le bouton Recharger pour réessayer. Si cette erreur persiste, vous pouvez cliquer sur le bouton rapport pour nous envoyer le journal des erreurs.",
    errorReload: "Recharger",
    errorReport: "Signaler",
  },
  it: {
    about: "Info",
    about_1: "Si prega di inviare commenti, suggerimenti e correzioni!",
    about_2: "Per informazioni, suggerimenti o aiuto, visitare il sito Web",
    about_3:
      "Si prega di coprire la testa e rimuovere le scarpe per rispetto quando si utilizza questa app.",
    about_4: "Sundar Gutka utilizza",
    about_5:
      "- il database gurbani open source e API utilizzati in molte applicazioni gurbani, come SikhiToTheMax.",
    about_6: "Perdona gli errori [Bùll Ciùc Màf]",
    above_raag_headings: "Sopra i titoli raag ",
    anmol_lipi: "Anmòl Leppi",
    app_version: "Versione dell'App",
    auto_scroll: "Scorrimento Automatico",
    bani_length: "Lunghezza delle Bani",
    bani_length_alert_1:
      "Nel corso degli ultimi secoli, ci sono stati molti ”sampardhas” o ”jathas” diversi che sono stati concepiti dai concetti fondamentali di Sikhi e della Gurmat. Questi esempi hanno spesso opinioni e pensieri diversi su alcuni aspetti della storia dei Sikh, Gurbani e Rehat. Cadono ancora sotto l'unione di Khalsa Panth e, soprattutto, di Akaal Takht. L'Akaal Takht è il più alto ordine e istituzione a cui tutti i sikh aderiscono.",
    bani_length_alert_2:
      "Queste differenze hanno anche portato a diverse raccomandazioni a proposito delle Baani compilate e Paath (preghiere) che leggiamo quotidianamente, il che rende difficile creare una singola app Sundar Gutka con un'unica versione di Paath in grado di soddisfare tutti.",
    bani_length_alert_3:
      "Pertanto abbiamo offerto la possibilità di selezionare le lunghezze di ciò che fai Paath che si applica a quattro deile Bani principale lette più spesso. Queste sono state strutturate in relazione alla lunghezza ma tutte hanno un minimo dello standard SGPC o rientrane nell'Akaal Takht. Come standard, non includiamo alcuna versione di sampardhas che sono stati scomunicati dall'Akaal Takht.",
    bani_length_alert_4:
      "Per coloro che potrebbero essere confusi su quale versione iniziare a leggere queste Banis, raccomandiamo di leggere la Bani più lunga perché più leggiamo e recitiamo, meglio è per le nostre anime. Tuttavia, per i principianti, consigliamo di iniziare con l'impostazione ”breve” e modificare per aumentare l'impostazione della lunghezza in futuro una volta che si è a proprio agio, sicuri e hanno più tempo.",
    bani_length_alert_5: "Ecco qui le lunghezze e quali sampardhas le usano normalmente: -",
    bani_length_alert_6: "BREVE: questo è lo standard minimo SGPC / Akaal Takht.",
    bani_length_alert_7: "MEDIA: in genere letto dai seguaci di Akhand Kirtani Jatha e altri.",
    bani_length_alert_8: "LUNGA: in genere letto dai seguaci di Damdami Taksaal e altri.",
    bani_length_alert_9: "LUNGHISSIMA: il più popolare tra i seguaci di Buddha Dal.",
    bani_length_message_1:
      "A causa del feedback degli utenti, sappiamo che ci sono molte varianti di alcune Banis là fuori che le persone leggono. Per assicurarti di ottenere la migliore esperienza dalla nostra app, scegli una delle preferenze di seguito che meglio descrive le sue preferenze.",
    bani_length_message_2:
      "Questa sarà un'impostazione unica, ma puoi modificare queste impostazioni in qualsiasi momento andando su Impostazioni > Lunghezza delle Bani nell'app.",
    bani_options: "Opzioni delle Bani",
    baniDB: "BaniDB",
    banidb_living_default: "BaniDB (default) ",
    bookmarks: "Segnalibri",
    cancel: "Annulla",
    choose_your_preference: "Scegli la sua preferenza",
    click_more_info: "Clicca qui per maggiori informazioni",
    collect_statistics: "Raccogliere Statistiche",
    colored_words: "Parole a Colori",
    confirm_exit: "Uscire Sunder Gutka?",
    created_by: "Creato da",
    current_saroops_default: "Saroope attuale (default)",
    dark_mode: "Modalità scura",
    default: "Default",
    delete: "Eliminare",
    display_options: "Opzioni di visualizzazione",
    donate: "Donare",
    edit_bani_order: "Modifica l'ordine delle Bani",
    en_translations: "Traduzioni in inglese",
    english: "Inglese",
    es_translations: "Traduzioni in spagnolo",
    exit: "Uscire",
    exit_sundar_gutka: "Uscire Sunder Gutka",
    extra_large: "Grandissima",
    extra_long: "Lunghissima",
    extra_small: "Picolissima",
    font_face: "Il font",
    font_size: "Dimensione del font",
    gradient_background: "Sfondo sfumato",
    gurbani_akhar_default: "Gurbani Akhar (default)",
    gurbani_akhar_heavy: "Gourbani Akhar Grasso",
    gurbani_akhar_think: "Gourbani Akhar Spesso",
    hide_status_bar: "Nascondere la barra di stato",
    hindi: "Lingua hindi",
    iGurbani: "iGurbani",
    ipa: "Alfabeto fonetico internazionale",
    keep_awake: "Restare sveglio lo schermo",
    khalis_foundation: "La fondazione Khalis",
    language: "Lingua",
    large: "Grande",
    larivaar: "Larivaar",
    larivaar_assist: "larivaar Assist",
    long: "Lunga",
    manglacharan_position: "Posizione del Manglacharan",
    mast_sabh_mast: "Mast Sabh Mast",
    medium: "Media",
    need_help_deciding: "Bisogno di aiuto nel decidere?",
    notification_text: "Testo di notifica",
    ok: "Va bene",
    other_options: "Altre opzioni",
    padchhed_settings: "Impostazioni Padsced",
    paragraph_mode: "Modalità paragrafo",
    pick_a_time: "Scegli l'ora",
    pu_translations: "Traduzioni in punjabi",
    reminder_options: "Opzioni di promemoria",
    reminder_sound: "Suono di promemoria",
    reminders: "Promemoria",
    reset: "Resettare",
    reset_reminder_text: "Desideri ripristinare i promemoria sui valori predefiniti?",
    reset_reminders: "Resettare i promemoria",
    sat_subham_sat_default: "Sat Subham Sat (default)",
    set_reminder_options: "Imposta le opzioni di promemoria",
    settings: "Impostazioni",
    shahmukhi: "Shahmukhi",
    short: "Breve",
    show_vishraams: "Mostra Vishraams",
    small_default: "Piccola (default)",
    sttm2: "SSTM 2",
    sundar_gutka: "Sundar Gutka",
    tap_more_info: "",
    time_for: "È l'ora di",
    translations: "Traduzioni",
    transliteration: "Traslitterazioni",
    vishraam_options: "Opzioni di Vishraam",
    vishraam_source: "Origine di Vishraam",
    waheguru_soul: "Waheguru Soul",
    wake_up_jap: "Svegliasi Jap",
    fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
    sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    khalsa_sundar_gutka: "Kwlsw suMdr gutkw",
    theme: "Tema",
    errorTitle: "Qualcosa è andato storto",
    errorMessage:
      "Fare clic sul pulsante Ricarica per riprovare. Se l'errore persiste, puoi fare clic sul pulsante di segnalazione per inviarci il registro degli errori.",
    errorReport: "Rapporto",
    errorReload: "Ricaricare",
  },
  es: {
    about: "Sobre Nosotros",
    about_1: "¡Agradecemos sus comentarios, sugerencias y correcciones!",
    about_2: "Para información, sugerencias o ayuda, visite",
    about_3: "Por respeto, cúbrase la cabeza y quítense los zapatos cuando uses esta aplicación.",
    about_4: "Sundar Gutka utiliza",
    about_5:
      "- la base de datos de código abierto de Gurbani y la API utilizada en muchas aplicaciones de Gurbani, como SikhiToTheMax.",
    about_6: "Que se perdone los errores [Búl Chúk Máf]",
    above_raag_headings: "Por encima de los títulos raag ",
    anmol_lipi: "Anmól Lippi ",
    app_version: "Versión de la aplicación",
    auto_scroll: "Desplazamiento automático",
    bani_length: "Largueza de las Bani",
    bani_length_alert_1:
      "A lo largo de los últimos siglos, ha habido muchos ”sampardhas” o ”jathas” diferentes que se han concebido a partir de los conceptos centrales de Sikhi y Gurmat.  Estos sampardhas a menudo tienen diferentes opiniones y pensamientos sobre algunos aspectos de la historia sikh, Gurbani y Rehat, pero aún caen colectivamente bajo el Khalsa Panth unido y, lo más importante, el Akaal Takht.El Akaal Takht es el más alto orden e institución a la que se adhieren todos los sikhs.",
    bani_length_alert_2:
      "Estas diferencias también han dado lugar a diferentes recomendaciones sobre Baanis y Paath (oraciones) compiladas que leemos a diario, lo que dificulta la creación de una sola aplicación Sundar Gutka con una única versión de Paath que satisfaga a todos.",
    bani_length_alert_3:
      "Por lo tanto, hemos creado la opción de seleccionar longitudes de lo que hace Paath que se aplica a cuatro de los principales Banis leídos con mayor frecuencia. Estos se han estructurado en relación con la longitud, pero todos tienen un mínimo del estándar SGPC o caen bajo el Akaal Takht. Como estándar, no incluimos ninguna versión que sea realizada por sampardhas excomulgada por el Akaal Takht.",
    bani_length_alert_4:
      "For those who are confused about from which version to start reading these Banis, we recommend reading the longest Bani because the more we read and recite, the better it will be for our souls. However, for beginners, we suggest starting with the ”short” setting and changing to increase length in the future once you are comfortable, confident, and have more time.",
    bani_length_alert_5:
      "Aquí hay un desglose de las longitudes y qué sampard las usa típicamente:",
    bani_length_alert_6: "CORTA: Este es el estándar mínimo SGPC / Akaal Takht.",
    bani_length_alert_7: "MEDIA: Típicamente leído por seguidores de Akhand Kirtani Jatha y otros.",
    bani_length_alert_8: "LARGA: Típicamente leído por seguidores de Damdami Taksaal y otros.",
    bani_length_alert_9: "LARGISIMA: El más popular entre los seguidores de Buda Dal.",
    bani_length_message_1:
      "Según los comentarios de los usuarios, sabemos que hay muchas variaciones diferentes de ciertos Banis que la gente lee. Para asegurarse de obtener la mejor experiencia de nuestra aplicación, elija una de las siguientes preferencias que mejor describa sus preferencias.",
    bani_length_message_2:
      "Esta será una configuración única, pero puede cambiar esta configuración en cualquier momento yendo a Configuración> Longitud de las Bani en la aplicación.",
    bani_options: "Opciones de las Bani",
    baniDB: "BaniDB",
    banidb_living_default: "BaniDB (predeterminados)",
    bookmarks: "Marcadores",
    cancel: "Cancelar",
    choose_your_preference: "Elige su preferencia",
    click_more_info: "Haga clic aquí para más información",
    collect_statistics: "Recopilar estadísticas",
    colored_words: "Palabras resaltadas",
    confirm_exit: "¿Salir de Sunder Gutka?",
    created_by: "Creado por",
    current_saroops_default: "Sarupas Actuales",
    dark_mode: "Modo oscuro",
    default: "Predeterminados",
    delete: "Borrar",
    display_options: "Opciones de visualización ",
    donate: "Donar",
    edit_bani_order: "Cambiar el orden de las Bani",
    en_translations: "Traducciones al inglés",
    english: "Inglés",
    es_translations: "Traducciones al castillano",
    exit: "Salir",
    exit_sundar_gutka: "Salir de Sunder Gutka",
    extra_large: "Grandisima",
    extra_long: "Largisima",
    extra_small: "Pequeñisima",
    font_face: "Fuente",
    font_size: "Tamaño de la fuente",
    gradient_background: "Fondo degradado",
    gurbani_akhar_default: "Gurbani Akhar (predeterminados)",
    gurbani_akhar_heavy: "Gurbani Akhar Fuerte",
    gurbani_akhar_think: "Gurbani Akhar Denso",
    hide_status_bar: "Ocultar la barra de estado",
    hindi: "Idioma hindú",
    iGurbani: "iGurbani",
    ipa: "Alfabeto Fonético Internacional",
    keep_awake: "Mantener la pantalla despierta",
    khalis_foundation: "Fundación Khalis",
    language: "Idioma",
    large: "Grande",
    larivaar: "Larivaar",
    larivaar_assist: "Asistencia de Larivaar",
    long: "Larga",
    manglacharan_position: "Posición mangalcharan",
    mast_sabh_mast: "Mast Sabh Mast",
    medium: "Mediana",
    need_help_deciding: "¿Necesita ayuda para decidir?",
    notification_text: "Texto de notificación",
    ok: "De acuerdo",
    other_options: "Otras opciones",
    padchhed_settings: "Ajustes Padchhed",
    paragraph_mode: "Modo párrafo",
    pick_a_time: "Elige la ora",
    pu_translations: "Traducciones al punjabi",
    reminder_options: "Opciones de recordatorio",
    reminder_sound: "Sonido recordatorio",
    reminders: "Recordatorios",
    reset: "Reiniciar",
    reset_reminder_text: "¿Desea restaurar los recordatorios a los valores predeterminados?",
    reset_reminders: "Restablecer los recordatorios",
    sat_subham_sat_default: "Sat Subham Sat (predeterminados)",
    set_reminder_options: "Establecer las opciones de recordatorio",
    settings: "Ajustes",
    shahmukhi: "Shahmukhi",
    short: "Corta",
    show_vishraams: "Muestra Vishraams",
    small_default: "Pequeña (predeterminados)",
    sttm2: "STTM 2",
    sundar_gutka: "Sundar Gutka",
    tap_more_info: "",
    time_for: "Es ora de",
    translations: "Traducciones",
    transliteration: "Transcripciónes",
    vishraam_options: "Opciones de Vishraam",
    vishraam_source: "Origen de Vishraam",
    waheguru_soul: "Waheguru Soul",
    wake_up_jap: "Despierta Jap",
    khalsa_sundar_gutka: "Kwlsw suMdr gutkw",
    fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
    sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    theme: "Tema",
    errorTitle: "Algo salió mal",
    errorMessage:
      "Haga clic en el botón Recargar para volver a intentarlo. Si este error persiste, puede hacer clic en el botón de informe para enviarnos el registro de errores.",
    errorReload: "Recargar",
    errorReport: "Reporte",
  },
});

export default Strings;
