import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
    "en-US": {
        about: "About",
        about_1: "We welcome your comments, suggestions, and corrections!",
        about_2: "For information, suggestions, or help, visit us at",
        about_3: "Please respectfully cover your head and remove your shoes when using this app.",
        about_4: "Sundar Gutka utilizes",
        about_5: "- the open source gurbani database and api used in many gurbani applications, such as SikhiToTheMax.",
        about_6: "Bhul Chuk Maaf!",
        above_raag_headings: "Above Raag Headings",
        anmol_lipi: "Anmol Lipi",
        app_version: "App Version",
        auto_scroll: "Auto Scroll",
        bani_length: "Bani Length",
        baniDB: "BaniDB",
        bani_options: "Bani Options",
        banidb_living_default: "BaniDB Living (default)",
        bookmarks: "Bookmarks",
        cancel: "Cancel",
        collect_statistics: "Collect Statistics",
        colored_words: "Colored Words",
        confirm_exit: "Are you sure you want to exit?",
        created_by: "Created By",
        current_saroops_default: "Current Saroops (default)",
        dark_mode: "Dark Mode",
        default: "Default",
        delete: "Delete",
        display_options: "Display Options",
        donate: "Donate",
        edit_bani_order: "Edit Bani Order",
        en_translations: "English Translations",
        english: "English",
        es_translations: "Spanish Translations",
        exit: "Exit",
        exit_sundar_gutka: "Exit Sundar Gutka",
        extra_large: "Extra Large",
        extra_long: "Extra Long",
        extra_small: "Extra Small",
        font_face: "Font Face",
        font_size: "Font Size",
        gradient_background: "Gradient Background",
        gurbani_akhar_default: "Gurbani Akhar (default)",
        gurbani_akhar_heavy: "Gurbani Akhar Heavy",
        gurbani_akhar_think: "Gurbani Akhar Thick",
        hide_status_bar: "Hide Status Bar",
        hindi: "Hindi",
        iGurbani: "iGurbani",
        ipa: "International Phonetic Alphabet",
        keep_awake: "Keep Screen Awake",
        khalis_foundation: "Khalis Foundation",
        language: "Language",
        large: "Large",
        larivaar: "Larivaar",
        long: "Long",
        manglacharan_position: "Manglacharan Position",
        mast_sabh_mast: "Mast Sabh Mast",
        medium: "Medium",
        notification_text: "Notification Text",
        ok: "OK",
        other_options: "Other Options",
        padchhed_settings: "Padchhed Settings",
        paragraph_mode: "Paragraph Mode",
        pick_a_time: "Pick a Time",
        pu_translations: "Punjabi Translations",
        reminder_options: "Reminder Options",
        reminder_sound: "Reminder Sound",
        reminders: "Reminders",
        reset: "Reset",
        reset_reminder_text: "Do you want to restore reminders to the default values?",
        reset_reminders: "Reset Reminders",
        sat_subham_sat_default: "Sat Subham Sat (default)",
        set_reminder_options: "Set Reminder Options",
        settings: "Settings",
        shahmukhi: "Shahmukhi",
        short: "Short",
        show_vishraams: "Show Vishraams",
        small_default: "Small (default)",
        sttm2: "STTM 2",
        sundar_gutka: "Sundar Gutka",
        time_for: "Time for",
        translations: "Translations",
        transliteration: "Transliteration",
        vishraam_options: "Vishraam Options",
        vishraam_source: "Vishraam Source",
        waheguru_soul: "Waheguru Soul",
        wake_up_jap: "Wake Up Jap",
        fateh: "<> sRI vwihgurU jI kI Piqh ]",
        sg_title: "suMdr gutkw",
    }
});

module.exports = Strings;