import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
    "en-US": {
        about: "About",
        about_1: "We welcome your comments, suggestions, and corrections!",
        about_2: "For information, suggestions, or help, visit us at",
        about_3: "Please respectfully cover your head and remove your shoes when using this app.",
        about_4: "Sundar Gutka utilizes",
        about_5: "- the open source gurbani database and api used in many gurbani applications, such as SikhiToTheMax.",
        about_6: "Bhul Chuk Maaf!",
        above_raag_headings: "Above Raag Headings",
        anmol_lipi: "Anmol Lipi",
        app_version: "App Version",
        auto_scroll: "Auto Scroll",
        bani_length: "Bani Length",
        bani_length_alert_1: "Throughout the past few centuries, there have been many different “sampardhas” or “jathas” that have been conceived from the core concepts of Sikhi and Gurmat. These sampardhas often have different opinions and thoughts about some aspects of Sikh history, Gurbani and Rehat, but still fall collectively under the united Khalsa Panth and, most importantly, the Akaal Takht. The Akaal Takht is the highest order and institution that all Sikhs adhere to.",
        bani_length_alert_2: "These differences have also brought about different recommendations about compiled Baanis and the Paath (prayers) that we read on a daily basis which makes it difficult to create a single Sundar Gutka app with a single version of Paath that would satisfy everyone.",
        bani_length_alert_3: "We therefore have created the option to select lengths of what Paath you do that apply to four of the main Banis read most often. These have been structured in relation to length but all have a minimum of the SGPC standard or fall under the Akaal Takht. We do not include any versions that are by sampardhas excommunicated by the Akaal Takht as a standard.",
        bani_length_alert_4: "For those who may be confused about which version to begin reading these Banis, we recommend reading the longest Bani because the more we read and recite, the better it is for our souls. However, for beginners, we would suggest to start with the “short” setting and change to increase the length setting in future once you are comfortable, confident and have more time.",
        bani_length_alert_5: "Here is a breakdown of the lengths and which sampardhas typically use them:-",
        bani_length_alert_6: "SHORT: This is the minimum SGPC/Akaal Takht standard.",
        bani_length_alert_7: "MEDIUM: Typically read by followers of the Akhand Keertani Jatha and others.",
        bani_length_alert_8: "LONG: Typically read by followers of Damdami Taksaal and others.",
        bani_length_alert_9: "EXTRA LONG: Most popular amongst followers of Buddha Dal.",
        bani_length_message_1: "Based on user feedback, we know there are many different variations of certain Banis out there that people read. To make sure you get the best experience from our app, please choose a preference below which best describes your preferences.",
        bani_length_message_2: "This will be a one-time setup, but you can change these settings at any time by going to Settings > Bani Length in the app.",
        baniDB: "BaniDB",
        bani_options: "Bani Options",
        banidb_living_default: "BaniDB Living (default)",
        bookmarks: "Bookmarks",
        cancel: "Cancel",
        choose_your_preference: "Choose your preference",
        collect_statistics: "Collect Statistics",
        colored_words: "Colored Words",
        confirm_exit: "Are you sure you want to exit?",
        created_by: "Created By",
        current_saroops_default: "Current Saroops (default)",
        dark_mode: "Dark Mode",
        default: "Default",
        delete: "Delete",
        display_options: "Display Options",
        donate: "Donate",
        edit_bani_order: "Edit Bani Order",
        en_translations: "English Translations",
        english: "English",
        es_translations: "Spanish Translations",
        exit: "Exit",
        exit_sundar_gutka: "Exit Sundar Gutka",
        extra_large: "Extra Large",
        extra_long: "Extra Long",
        extra_small: "Extra Small",
        font_face: "Font Face",
        font_size: "Font Size",
        gradient_background: "Gradient Background",
        gurbani_akhar_default: "Gurbani Akhar (default)",
        gurbani_akhar_heavy: "Gurbani Akhar Heavy",
        gurbani_akhar_think: "Gurbani Akhar Thick",
        hide_status_bar: "Hide Status Bar",
        hindi: "Hindi",
        iGurbani: "iGurbani",
        ipa: "International Phonetic Alphabet",
        keep_awake: "Keep Screen Awake",
        khalis_foundation: "Khalis Foundation",
        language: "Language",
        large: "Large",
        larivaar: "Larivaar",
        larivaar_assist: "Larivaar Assist",
        long: "Long",
        manglacharan_position: "Manglacharan Position",
        mast_sabh_mast: "Mast Sabh Mast",
        medium: "Medium",
        need_help_deciding: "Need help deciding?",
        notification_text: "Notification Text",
        ok: "OK",
        other_options: "Other Options",
        padchhed_settings: "Padchhed Settings",
        paragraph_mode: "Paragraph Mode",
        pick_a_time: "Pick a Time",
        pu_translations: "Punjabi Translations",
        reminder_options: "Reminder Options",
        reminder_sound: "Reminder Sound",
        reminders: "Reminders",
        reset: "Reset",
        reset_reminder_text: "Do you want to restore reminders to the default values?",
        reset_reminders: "Reset Reminders",
        sat_subham_sat_default: "Sat Subham Sat (default)",
        set_reminder_options: "Set Reminder Options",
        settings: "Settings",
        shahmukhi: "Shahmukhi",
        short: "Short",
        show_vishraams: "Show Vishraams",
        small_default: "Small (default)",
        sttm2: "STTM 2",
        sundar_gutka: "Sundar Gutka",
        tap_more_info: "Tap here for more information",
        time_for: "Time for",
        translations: "Translations",
        transliteration: "Transliteration",
        vishraam_options: "Vishraam Options",
        vishraam_source: "Vishraam Source",
        waheguru_soul: "Waheguru Soul",
        wake_up_jap: "Wake Up Jap",
        fateh: "<> sRI vwihgurU jI kI Piqh ]",
        khalsa_sundar_gutka: "Kwlsw suMdr gutkw",
        sg_title: "suMdr gutkw",
    },
    "hi": {
        about: "हमारे बारे",
        about_1: "हम आप के सुझाव और टिप्पणिओं का स्वागत करते हैं।",
        about_2: "और जानकारी, मदद या सुझाव के लिए यहां जाएँ।",
        about_3: "एप्प का इस्तेमाल करने से पहले सत्कार सहत अपने जूते उतार के सिर ढक लें",
        about_4: "सुंदर गुटका इस्तेमाल करता है",
        about_5: "-ओपन सोर्स डाटाबेस और बहुत सारी गुरबाणी एप्प जैसे SikhiToTheMax",
        about_6: "भूलों की क्षमा !",
        above_raag_headings: "राग शीर्षक",
        anmol_lipi: "अनमोल लिपि",
        app_version: "एप्प वर्जन",
        auto_scroll: "ऑटो स्क्रॉल",
        bani_length: "बाणी लंबाई",
        bani_length_alert_1: "पिछले कुछ सदियों में, कई सम्प्रदायें और संगठन पैदा हुई हैं, जो सिख सिद्धांत और गुरुमत पर केंद्रित हैं। हालांकि इन संप्रदायों में सिख इतिहास, गुरबानी और अनुपालन पर मतभेद रहे हैं, पर वे पूर्ण रूप से  खालसा पंथ का हिस्सा बने हुए हैं और उच्चतम अकाल तख्त के बैनर तले ही रह रहे हैं।",
        bani_length_alert_2: "इन मतभेदों के कारण, नितनेम की बाणिओं  की लंबाई पर अलग- अलग निर्देश मिलते रहे हैं। इस कारण से, हर एक को संतुष्ट कर देने वाला एक  सुंदर गुटका ऐप बनाना मुश्किल है।",
        bani_length_alert_3: "इसीलिए हमने इस ऐप में चार सबसे ज्यादा पढ़ी जाने वाली बाणिओं की लंबाई चुनने की सुविधा दी है। इन चयनों को बाणी की लंबाई के अनुसार व्यवस्थित किया गया है लेकिन सभी बाणी अकाल तख्त द्वारा अनुमोदित मानकों के अनुसार हैं। हमने इस एप में अकाल तख्त द्वारा पंथ से बाहर की हुई किसी भी संप्रदाय द्वारा इस्तेमाल किए जाने वाली बाणी नहीं शामिल की है।",
        bani_length_alert_4: "यदि आप असमंजस में हैं कि किस बाणी के साथ शुरू करें, तो हमारी सलाह सबसे लंबी बाणी है क्योंकि जितना अधिक हम बाणी का अभ्यास करेंगे, हमारी आत्मा के लिए उतना ही अच्छा होगा। यदि आप एकदम नए हैं तो आप सबसे छोटी बाणी के साथ शुरुआत कर सकते हैं और जैसे आपका नाम अभ्यास बढ़ता है, आप अधिक बाणी पढ़ सकते हैं।",
        bani_length_alert_5: "बाणिओं को व्यवस्थित उनकी लंबाई और सम्प्रदा के हिसाब से किआ गया है",
        bani_length_alert_6: "छोटी - यह बाणी अकाल तख्त साहिब से परवाणित कम से कम आदेशों के हिसाब से है।",
        bani_length_alert_7: "मध्यम - अखंड कीर्तनी जथा तथा और।",
        bani_length_alert_8: "लम्बी - दमदमी टकसाल तथा और जथे।",
        bani_length_alert_9: "बहुत लम्बी - बुड्ढा दल",
        bani_length_message_1: "इस एप में अपना तज़ुर्बा और उत्तम करने के लिए अपनी पसंद के हिसाब से बाणी का चयन करें",
        bani_length_message_2: "यह चयन आपको एक बार ही करना पड़ेगा लेकिन आप कभी भी settings >bani  length में जाकर अपना चयन बदल सकते हैं।",
        baniDB: "BaniDB",
        bani_options: "बाणी विकल्प",
        banidb_living_default: "BaniDB जीवित (मूल)",
        bookmarks: "बुकमार्क",
        cancel: "रहने दो",
        choose_your_preference: "अपनी पसंद के हिसाब से चयन करें",
        collect_statistics: "आंकड़े इकट्ठे करो",
        colored_words: "रंगदार शब्द",
        confirm_exit: "किआ आप बाहर जाना चाहते हो?",
        created_by: "बनाई गयी",
        current_saroops_default: "मौजूदा सरूप",
        dark_mode: "गहरा mode",
        default: "मूल",
        delete: "मिटा दे",
        display_options: "डिस्प्ले विकल्प",
        donate: "दान",
        edit_bani_order: "बाणी की तरतीब बदलें",
        en_translations: "अंग्रेजी अनुवाद",
        english: "अंग्रेजी",
        es_translations: "स्पैनिश अनुवाद",
        exit: "बाहर निकलें",
        exit_sundar_gutka: "सुंदर गुटके से बाहर निकलें",
        extra_large: "बहुत बड़ा",
        extra_long: "बहुत लम्बा",
        extra_small: "बहुत छोटा",
        font_face: "फॉन्ट का नाम",
        font_size: "फॉन्ट का आकार",
        gradient_background: "ढाल पृष्ठभूमि",
        gurbani_akhar_default: "गुरबाणी अक्षर (मूल)",
        gurbani_akhar_heavy: "गुरबाणी अक्षर भारी ",
        gurbani_akhar_think: "गुरबाणी अक्षर मोटे",
        hide_status_bar: "स्टेटस बार को छिपा दें",
        hindi: "हिंदी",
        iGurbani: "iGurbani",
        ipa: "इंटरनेशनल फ़ोनेटिक एल्फाबेट",
        keep_awake: "स्क्रीन को चलती रखें",
        khalis_foundation: "खालिस फाउंडेशन",
        language: "भाषा",
        large: "बड़ा",
        larivaar: "लड़ीवार",
        larivaar_assist: "लड़ीवार मदद के साथ",
        long: "लम्बा",
        manglacharan_position: "मंगलाचरण की जगह",
        mast_sabh_mast: "मस्त सभ मस्त",
        medium: "मध्यम",
        need_help_deciding: "चयन करने में मदद चाहिए?",
        notification_text: "नोटीफिकेशन अक्षर",
        ok: "ठीक",
        other_options: "और विकल्प",
        padchhed_settings: "पदच्छेद विकल्प",
        paragraph_mode: "पैरा विकल्प",
        pick_a_time: "समें का चुनाव",
        pu_translations: "पंजाबी अनुवाद",
        reminder_options: "याद करवाएं",
        reminder_sound: "याद करवाने वाली ध्वनि",
        reminders: "अनुस्मारक",
        reset: "शुरू से",
        reset_reminder_text: "किआ आप याद करवाने विकल्प मूल रूप में लगाने चाहते हो?",
        reset_reminders: "याद करवाने वाले विकल्प शुरू से करो",
        sat_subham_sat_default: "सत सुभम सत",
        set_reminder_options: "याद करवाने वाले विकल्प करें",
        settings: "विकल्प",
        shahmukhi: "शाहमुखी",
        short: "छोटे",
        show_vishraams: "विश्राम दिखलायें",
        small_default: "छोटे (मूल)",
        sttm2: "STTM 2",
        sundar_gutka: "सुंदर गुटका",
        tap_more_info: "और जानकारी के लिए यहां छुएं",
        time_for: "समां है",
        translations: "अनुवाद",
        transliteration: "अक्षरी अनुवाद",
        vishraam_options: "विश्राम विकल्प",
        vishraam_source: "विश्राम का स्रोत",
        waheguru_soul: "वाहेगुरु रूह",
        wake_up_jap: "अमृत समें जाप",
        fateh: "ੴ श्री वाहेगुरु जी की फतेह",
        khalsa_sundar_gutka: "खालसा सुंदर गुटका",
        sg_title: "सुंदर गुटका",
    },
    "pa": {
        about: "ਸਾਡੇ ਬਾਰੇ",
        about_1: "ਅਸੀਂ ਤੁਹਾਡੀਆਂ ਟਿੱਪਣੀਆਂ ਅਤੇ ਸੁਝਾਵਾਂ ਨੂੰ ਖਿੜੇ ਮੱਥੇ ਪ੍ਰਵਾਨ ਕਰਦੇ ਆ।",
        about_2: "ਹੋਰ ਜਾਣਕਾਰੀ, ਸੁਝਾਅ ਯਾ ਮੱਦਦ ਲਈ ਏਥੇ ਜਾਓ",
        about_3: "ਐਪ ਨੂੰ ਵਰਤਣ ਲੱਗੇ ਸਤਿਕਾਰ ਸਹਿਤ ਆਪਣੇ ਜੋੜੇ ਲਾਹ ਕੇ ਸਿਰ ਢੱਕ ਲਓ",
        about_4: "ਸੁੰਦਰ ਗੁਟਕਾ ਵਰਤਦਾ ਹੈ",
        about_5: "- ਓਪਨ ਸੋਰਸ ਗੁਰਬਾਣੀ ਡਾਟਾਬੇਸ ਅਤੇ ਬਹੁਤ ਸਾਰੀਆਂ ਗੁਰਬਾਣੀ ਐਪਾਂ ਜਿਵੇਂ ਕੇ SikhiToTheMax",
        about_6: "ਭੁੱਲ ਚੁੱਕ ਮਾਫ !",
        above_raag_headings: "ਰਾਗ ਸਿਰਨਾਵੇਂ",
        anmol_lipi: "ਅਨਮੋਲ ਲਿਪੀ",
        app_version: "ਐਪ ਵਰਜ਼ਨ",
        auto_scroll: "ਆਟੋ ਸਕਰੋਲ",
        bani_length: "ਬਾਣੀ ਲੰਬਾਈ",
        bani_length_alert_1: "ਬੀਤੀਆਂ ਕੁਝ ਸਦੀਆਂ ਦੌਰਾਨ ਅਨੇਕਾਂ ਅਜਿਹੀਆਂ ਸੰਪਰਦਾਵਾਂ ਤੇ ਜੱਥੇਬੰਦੀਆਂ ਪੈਦਾ ਹੋਈਆਂ ਜਿਨ੍ਹਾਂ ਦਾ ਧੁਰਾ ਸਿੱਖੀ ਸਿਧਾਂਤ ਅਤੇ ਗੁਰਮਤਿ ਰਿਹਾ। ਭਾਵੇਂ ਇਹਨਾਂ ਸੰਪਰਦਾਵਾਂ ਵਿੱਚ ਸਿੱਖ ਇਤਿਹਾਸ, ਗੁਰਬਾਣੀ ਅਤੇ ਰਹਿਤ ਨੂੰ ਲੈ ਕੇ ਆਪਸੀ ਮਤਭੇਦ ਰਹੇ ਹਨ, ਪਰ ਸਮੂਹ ਤੌਰ ਤੇ ਖਾਲਸਾ ਪੰਥ ਦੇ ਹਿੱਸੇ ਵਜੋਂ ਹੀ ਵਿਚਰੀਆਂ ਹਨ ਤੇ ਸੱਭ ਤੋਂ ਵੱਧ ਕੇ ਸਰਬ ਉੱਚ ਅਕਾਲ ਤਖਤ ਦੇ ਝੰਡੇ ਹੇਠ ਹੀ ਰਹੀਆਂ (ਰਹਿੰਦੀਆਂ) ਹਨ।",
        bani_length_alert_2: "ਇਹਨਾਂ ਵਖਰੇਵਿਆਂ ਦੇ ਕਾਰਨ ਨਿਤਨੇਮ ਦੀਆਂ ਸੰਪਾਦਿਤ ਬਾਣੀਆਂ ਦੀ ਲੰਬਾਈ ਉੱਤੇ ਵੀ ਵੱਖੋ ਵੱਖਰੀਆਂ ਹਦਾਇਤਾਂ ਮਿਲਦੀਆਂ ਰਹੀਆਂ ਹਨ। ਇਸ ਕਾਰਨ ਹਰੇਕ ਮਾਈ ਭਾਈ ਦੀ ਸੰਤੁਸ਼ਟੀ ਕਰਵਾ ਸਕਣ ਵਾਲੀ ਇੱਕ ਸਰਬ ਪਰਵਾਨਤ ਸੁੰਦਰ ਗੁਟਕਾ ਐਪ (ਜੁਗਤ) ਤਿਆਰ ਕਰਨੀ ਔਖੀ ਹੋ ਜਾਂਦੀ ਰਹੀ ਹੈ।",
        bani_length_alert_3: "ਏਸੇ ਲਈ ਅਸੀਂ ਇਸ ਐਪ (ਜੁਗਤ) ਵਿੱਚ ਆਮ ਤੌਰ ਤੇ ਚਾਰ ਸੱਭ ਤੋਂ ਵੱਧ ਪੜ੍ਹੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਬਾਣੀਆਂ ਦੀ ਲੰਬਾਈ ਚੁਣਨ ਦੀ ਸਹੂਲਤ ਦਿੱਤੀ ਹੈ। ਇਹਨਾਂ ਚੋਣਾਂ ਨੂੰ ਬਾਣੀ ਦੀ ਲੰਬਾਈ ਦੇ ਹਿਸਾਬ ਨਾਲ ਤਰਤੀਬ ਦਿੱਤੀ ਗਈ ਹੈ ਪਰ ਸਾਰੀਆਂ ਹੀ ਬਾਣੀਆਂ ਅਕਾਲ ਤਖਤ ਸਾਹਬ ਵੱਲ੍ਹੋਂ ਪ੍ਰਵਾਨਤ ਮਿਆਰਾਂ ਅਨੁਸਾਰ ਹਨ। ਅਸੀਂ ਅਕਾਲ ਤਖਤ ਤੋਂ ਛੇਕੀ ਹੋਈ ਕਿਸੇ ਵੀ ਸੰਪਰਦਾ ਵੱਲ੍ਹੋਂ ਵਰਤੀ ਜਾਂਦੀ ਬਾਣੀ ਦੀ ਕੋਈ ਵੀ ਵੰਨਗੀ ਇਸ ਜੁਗਤ ਵਿੱਚ ਨਹੀਂ ਪਾਈ",
        bani_length_alert_4: "ਜੇ ਤੁਸੀਂ ਇਸ ਉਲਝਣ ਵਿੱਚ ਹੋ ਕੇ ਕਿਸ ਬਾਣੀ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋਂ, ਸਾਡੀ ਸਲਾਹ ਹੈ ਸਭ ਤੋਂ ਲੰਬੀ ਬਾਣੀ ਕਿਉਂਕਿ ਜਿੰਨਾ ਜ਼ਿਆਦਾ ਅਸੀਂ ਬਾਣੀ ਅਭਿਆਸ ਕਰਾਂਗੇ, ਸਾਡੀ ਰੂਹ ਲਈ ਉੰਨਾਂ ਹੀ ਵਧੀਆ ਹੈ।  ਜੇ ਤੁਸੀਂ ਬਿਲਕੁਲ ਨਵੇਂ ਹੋ ਤਾਂ ਤੁਸੀਂ ਸਭ ਤੋਂ ਛੋਟੀ ਬਾਣੀ ਤੋਂ ਵੀ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ ਤੇ ਜਿਵੇਂ ਜਿਵੇਂ ਤੁਹਾਡਾ ਨਾਮ ਅਭਿਆਸ ਵੱਧ ਦਾ ਹੈ, ਤੁਸੀਂ ਜ਼ਿਆਦਾ ਬਾਣੀ ਪੜ੍ਹ ਸਕਦੇ ਓ।",
        bani_length_alert_5: "ਬਾਣੀਆਂ ਦੀ ਤਰਤੀਬ ਉਨ੍ਹਾਂ ਦੀ  ਲੰਬਾਈ ਅਤੇ ਸੰਪਰਦਾਵਾਂ ਦੇ ਹਿਸਾਬ ਨਾਲ ਕੀਤੀ ਗਈ ਹੈ।",
        bani_length_alert_6: "ਛੋਟੀ - ਇਹ ਬਾਣੀ ਅਕਾਲ ਤਖਤ ਸਾਹਿਬ ਵਲ੍ਹੋ ਘੱਟੋ ਘੱਟ ਪ੍ਰਵਾਣਤ ਮਿਆਰਾਂ ਅਨੁਸਾਰ ਹੈ",
        bani_length_alert_7: "ਮੱਧਮ - ਅਖੰਡ ਕੀਰਤਨੀ ਜਥਾ ਅਤੇ ਹੋਰ।",
        bani_length_alert_8: "ਲੰਬੀ - ਦਮਦਮੀ ਟਕਸਾਲ ਅਤੇ ਹੋਰ ਜਥੇ",
        bani_length_alert_9: "ਬਹੁਤ ਲੰਬੀ - ਬੁੱਢਾ ਦਲ",
        bani_length_message_1: "ਇਸ ਜੁਗਤ ਨਾਲ ਆਪਣਾ ਤਜਰਬਾ ਹੋਰ ਵਧੀਆ ਕਰਨ ਲਈ ਆਪਣੀ ਪਸੰਦ ਦੇ ਹਿਸਾਬ ਨਾਲ ਬਾਣੀ ਦੀ ਲੰਬਾਈ ਦੀ ਚੋਣ ਕਰੋ।",
        bani_length_message_2: "ਇਹ ਚੋਣ ਤੁਹਾਨੂੰ ਇੱਕ ਵਾਰ ਹੀ ਕਰਨੀ ਪਵੇਗੀ ਪਰ ਤੁਸੀਂ ਕਦੇ ਵੀ settings > bani length ਚ ਜਾਕੇ ਆਪਣੀ ਚੋਣ ਬਦਲ ਸਕਦੇ ਹੋ।",
        baniDB: "BaniDB",
        bani_options: "ਬਾਣੀ ਚੋਣਾਂ",
        banidb_living_default: "BaniDB ਜੀਵਿਤ (ਮੂਲ)",
        bookmarks: "ਬੁੱਕਮਾਰਕ",
        cancel: "ਰਹਿਣ ਦਿਓ",
        choose_your_preference: "ਆਪਣੀ ਪਸੰਦ ਦੇ ਹਿਸਾਬ ਨਾਲ ਚੋਣ ਕਰੋ",
        collect_statistics: "ਅੰਕੜੇ ਕੱਠੇ ਕਰੋ",
        colored_words: "ਰੰਗਦਾਰ ਸ਼ਬਦ",
        confirm_exit: "ਕੀ ਤੁਸੀਂ ਬੰਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਓ?",
        created_by: "ਬਣਾਈ ਗਈ",
        current_saroops_default: "ਮੌਜੂਦਾ ਸਰੂਪ",
        dark_mode: "ਗੂੜ੍ਹਾ mode",
        default: "ਮੂਲ",
        delete: "ਮਿਟਾ ਦਿਓ",
        display_options: "ਡਿਸਪਲੇਅ ਚੋਣਾਂ",
        donate: "ਦਾਨ",
        edit_bani_order: "ਬਾਣੀ ਦੀ ਤਰਤੀਬ ਬਦਲੋ",
        en_translations: "ਅੰਗਰੇਜ਼ੀ ਤਰਜਮਾ",
        english: "ਅੰਗਰੇਜ਼ੀ",
        es_translations: "ਸਪੈਨਿਸ਼ ਤਰਜਮਾ",
        exit: "ਬਾਹਰ ਨਿੱਕਲੋ",
        exit_sundar_gutka: "ਸੁੰਦਰ ਗੁਟਕੇ ਤੋਂ ਬਾਹਰ ਨਿੱਕਲੋ",
        extra_large: "ਬਹੁਤ ਵੱਡਾ",
        extra_long: "ਬਹੁਤ ਲੰਬਾ",
        extra_small: "ਬਹੁਤ ਛੋਟਾ",
        font_face: "ਫੋਂਟ ਦਾ ਨਾਮ",
        font_size: "ਫੋਂਟ ਆਕਾਰ",
        gradient_background: "ਗਰੇਡੀਐਂਟ ਪਿਛੋਕੜ",
        gurbani_akhar_default: "ਗੁਰਬਾਣੀ ਅੱਖਰ (ਮੂਲ)",
        gurbani_akhar_heavy: "ਗੁਰਬਾਣੀ ਅੱਖਰ ਭਾਰੇ",
        gurbani_akhar_think: "ਗੁਰਬਾਣੀ ਅੱਖਰ ਮੋਟੇ",
        hide_status_bar: "ਸਟੇਟਸ ਬਾਰ ਨੂੰ ਲਘੋ ਦਿਓ",
        hindi: "ਹਿੰਦੀ",
        iGurbani: "iGurbani",
        ipa: "ਇੰਟਰਨੈਸ਼ਨਲ ਫੋਨੈਟਿਕ ਅਲਫਾਬੈਟ",
        keep_awake: "ਸਕਰੀਨ ਨੂੰ ਚਲਦੀ ਰੱਖੋ",
        khalis_foundation: "ਖਾਲਿਸ ਫਾਊਂਡੇਸ਼ਨ",
        language: "ਭਾਸ਼ਾ",
        large: "ਵੱਡਾ",
        larivaar: "ਲੜੀਵਾਰ",
        larivaar_assist: "ਲੜੀਵਾਰ ਮਦਦ ਦੇ ਨਾਲ",
        long: "ਲੰਬਾ",
        manglacharan_position: "ਮੰਗਲਾਚਰਨ ਦੀ ਥਾਂ",
        mast_sabh_mast: "ਮਸਤ ਸਭ ਮਸਤ",
        medium: "ਦਰਮਿਆਨਾ",
        need_help_deciding: "ਚੋਣ ਕਰਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
        notification_text: "ਨੋਟੀਫਿਕੇਸ਼ਨ ਅੱਖਰ",
        ok: "ਠੀਕ",
        other_options: "ਹੋਰ ਚੋਣਾਂ",
        padchhed_settings: "ਪਦਛੇਦ ਚੋਣ",
        paragraph_mode: "ਪੈਰਾ ਚੋਣ",
        pick_a_time: "ਸਮਾਂ ਚੁਣੋ",
        pu_translations: "ਪੰਜਾਬੀ ਤਰਜਮਾ",
        reminder_options: "ਯਾਦ ਕਰਵਾਓ",
        reminder_sound: "ਯਾਦ ਕਰਵਾਉਣ ਆਲੀ ਆਵਾਜ਼",
        reminders: "ਚੇਤੇ ਕਰਾਉਣ ਲਈ",
        reset: "ਨਵੇਂ ਸਿਰਿਓਂ",
        reset_reminder_text: "ਕੀ ਤੁਸੀਂ ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆਂ ਚੋਣਾਂ ਮੂਲ ਰੂਪ ਤੇ ਲਾਉਣੀਆਂ ਚਾਹੁੰਦੇ ਓ ?",
        reset_reminders: "ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆ ਚੋਣਾਂ ਨੂੰ ਨਵੇਂ ਸਿਰਿਓਂ ਕਰੋ",
        sat_subham_sat_default: "ਸਤ ਸੁਭਮ ਸਤ",
        set_reminder_options: "ਚੇਤੇ ਕਰਾਉਣ ਆਲੀਆਂ ਚੋਣਾਂ ਕਰੋ",
        settings: "ਸੈਟਿੰਗ",
        shahmukhi: "ਸ਼ਾਹਮੁਖੀ",
        short: "ਛੋਟੇ",
        show_vishraams: "ਵਿਸ਼ਰਾਮ ਵਿਖਾਓ",
        small_default: "ਛੋਟੇ(ਮੂਲ)",
        sttm2: "STTM 2",
        sundar_gutka: "ਸੁੰਦਰ ਗੁਟਕਾ",
        tap_more_info: "ਹੋਰ ਜਾਣਕਾਰੀ ਲਈ ਇਥੇ ਛੋਹੋ",
        time_for: "ਸਮਾਂ ਹੈ",
        translations: "ਤਰਜਮੇ",
        transliteration: "ਅੱਖਰੀ ਤਰਜਮਾ",
        vishraam_options: "ਵਿਸ਼ਰਾਮ ਚੋਣਾਂ",
        vishraam_source: "ਵਿਸ਼ਰਾਮ ਦਾ ਸਰੋਤ",
        waheguru_soul: "ਵਾਹਿਗੁਰੂ ਰੂਹ",
        wake_up_jap: "ਅੰਮ੍ਰਿਤ ਵੇਲੇ ਦਾ ਜਾਪੁ",
        fateh: "ੴ ਸ੍ਰੀ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹਿ",
        khalsa_sundar_gutka: "ਖਾਲਸਾ ਸੁੰਦਰ ਗੁਟਕਾ",
        sg_title: "ਸੁੰਦਰ ਗੁਟਕਾ",
    }
});

module.exports = Strings;